backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Build Page", name: "buildPage", widget: "hidden", default: "true"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Preview Image", name: "previewImage", widget: image}
      - {label: "Weather", name: "weather", widget: "string", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: Banner, name: banner, widget: object, fields: [
              {
                label:  Title,
                name:   title,
                widget: string
              },
              {
                label:  Subtitle,
                name:   subtitle,
                widget: string
              },
              {
                label:  Blurb,
                name:   blurb,
                widget: text
              }
            ]}
          - {label: FeaturesSection, name: featuresSection, widget: object, fields: [
              {
                label:  Title,
                name:   title,
                widget: string
              },
              {
                label:  Subtitle,
                name:   subtitle,
                widget: string
              },
              {
                label:  Blurb,
                name:   blurb,
                widget: text
              },
              {
                label:  Call To Action,
                name:   callToAction,
                widget: string
              },
              {
                label:  Features,
                name:   features,
                widget: list,
                fields: [{
                  label:  Title,
                  name:   title,
                  widget: string
                },
                {
                  label:  Blurb,
                  name:   blurb,
                  widget: text
                },
                {
                  label:  Icon Class,
                  name:   iconClass,
                  widget: string
                }]
              }
            ]}
          - {label: Contact Section, name: contactSection, widget: object, fields: [
              {
                label:  Title,
                name:   title,
                widget: string
              },
              {
                label:  Blurb,
                name:   blurb,
                widget: text
              },
              {
                label:  Call To Action,
                name:   callToAction,
                widget: string
              },
              {
                label:  Thank You Message,
                name:   thankYouMessage,
                widget: string
              }
            ]}
          - {label: Banner, name: banner, widget: object, fields: [
              {
                label:  Title,
                name:   title,
                widget: string
              },
              {
                label:  Subtitle,
                name:   subtitle,
                widget: string
              },
              {
                label:  Blurb,
                name:   blurb,
                widget: text
              },
              {
                label:  Image 1,
                name:   image1,
                widget: image
              },
              {
                label:  Image 2,
                name:   image2,
                widget: image
              },
              {
                label:  Image 3,
                name:   image3,
                widget: image
              },
              {
                label:  Image 4,
                name:   image4,
                widget: image
              },
            ]}
